sudo: required
dist: trusty

language: haxe

# haxe versions : http://haxe.org/website-content/downloads/versions.json

haxe:
  - "3.4.0"
  - development

matrix:
  allow_failures:
  - haxe: development
    
env:
  global:
  # travis encrypt GH_TOKEN=<access-token> -r DoclerLabs/hexMachina
  - secure: Y7k64lsVnGXXFyEttqcYONkQog9pynxGIXnJAa/sdbehdknjQooDQbqWbd2CDzHs1lp7I5kppD3oM8jjkd+7ZH0EjnhzPr2f1OzdcLN3djml2hrKaDr4EMrQW9K3pDCAKP2CtaQtbxjm2l5QHEUcjLe82d/dS5TgEemUPA7/JYM4afCoXpGnCVZcknf5PbR2W3hyFk1R9+8B++5MuH3pNMwZvYEWwzUQLV4GZppe22N7ZlFjLNKnZ9tOd4QcRT9528ujvIKR0K9antuJDBQKTCQqxCTcQmndDp0lEuBhfC9ZDlrMVTLbKUD4B/0g0wHlMKsiJIWo1L03Ec5aASRV4uKRC/4RSLqmY1EXDEuDb1xG4Pg4/NH2Qpqju0qHE/vT5jYNMr2rmnQpcXZEotyoJ70wtIKRR0iIwsSAvTI5SKyNBXg8Wpkqu83/03IfgFqCXPAvOmuv7Pp8zPtLNcz7XnjTiwRFSGvwOzX8jz/+JwCCagLCo6AEcCDT4HCj6hUtHfWdrcyBBHUD40rFJjEDyYyl5MX9yJonznwiWo8Nu3Gx5f4C5WmdEQpxuwUK5wz4uZdH3gpCu7LZyvjUxdPwJNRp5P0uAdptH/vLyVMSyxBG4yC+KFMjWmj65pk0hW0YdS0JcuzgLrtb4r0TvtyElcv04vN7i0sKhY3ai+63IJ8=
  - TRAVIS_NODE_VERSION="6.6.0"

install:
- haxelib git travix https://github.com/aliokan/travix.git --always
- haxelib newrepo
- haxelib git travix https://github.com/aliokan/travix.git --always
- haxelib git hexcore https://github.com/DoclerLabs/hexCore.git --always
- haxelib git hexunit https://github.com/DoclerLabs/hexLog.git --never
- haxelib git hexreflection https://github.com/DoclerLabs/hexReflection.git --never
- haxelib git hexannotation https://github.com/DoclerLabs/hexAnnotation.git --never
- haxelib git hexinject https://github.com/DoclerLabs/hexInject.git --never
- haxelib git hexcommand https://github.com/DoclerLabs/hexCommand.git --never
- haxelib git hexunit https://github.com/DoclerLabs/hexUnit.git --never

- haxelib dev hexmachina .
- haxelib path hexmachina
- haxelib install dox
- git clone https://github.com/chipshort/hexDoc-Theme.git hexdoctheme
- ls -all
# update node for deploy scripts
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

before_script:
  - git config --global user.email "laurent@geturl.net"
  - git config --global user.name "Travis-CI"
  
script:
- haxelib run travix php
- haxelib run travix neko;
- haxelib run travix flash -swf-version 10.1
- haxelib run travix js

before_deploy: "./.travis/pre-deploy.sh"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # travis encrypt <access-token> -r DoclerLabs/hexMachina
    secure: YmXdsL9wqp0jZ/m4VfWAb6sjwm8+3xWAGR3zUQDwr8tPz+pAjNNWxPywgf6iOYJ4rdppfnax/2ay2wrmOobFz159Np2XXmNsgC4xTicEDrFUfzkfUQIMteu/EGqbRbNPaFKRdWFIJcFAqyOuewU1q1w95SaSPSWPvX3UXRR5aaCW+cSErsOTkufxecN5FZawW4VpiOUDQkv69zlKrKddXbrpoKUTPHOob4frAkP3eDypUuwFrWi+3SkpzatjOW54fHyT4e4Lwpg5mJmny/Zh6l5FqbODmAaGf1OUvfNdgHKNn86intqsBv40oc2FQnOmDPkwDjS3MPC37L8jO0foyvLfWOc46xI7jsSm+05lJPyV5mZUHI6elyJ7gcWoSuFBmuDC3WRNcEjTgDAOM3E/15HGbJvVVAJ4Uy0whzoz2ONhQfZ/KC3GEJCbkmoj41MbV36uPm1hchdfDuhcmPucqurs6Hbe1TlknL+2sPkI/UR7FEDmdcCB3B4kFmVSTuO/abp0Xb/PAZMxiI+hdtfvhDAd1RdKfC5wKA7mDxj+jlHa/E1ErUSJqObxNGqxLZcmqRgWS8TSmYaotwo21PKoDsgJXfBOPFO/a0OtZGqhSdRuWBQAm3UQkzMYCwsxetQUjUuL0nRELz41MiL82N964il9WcmCD/H4svXU8Q46pIQ=
  file_glob: true
  file: "*.zip"
  overwrite: true
  on:
    repo: DoclerLabs/hexMachina
    tags: true

after_deploy: "./.travis/post-deploy.sh"

notifications:
  email:
    recipients:
    - francis_bourre@me.com
    - peterphonix@gmail.com
    - laurent@geturl.net
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/09a17f76453cb9d1c34d
    on_success: change
    on_failure: always
    on_start: never
