sudo: required
dist: trusty

language: haxe

# haxe versions : http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.2.1"
  - "3.4.0"
  - development

matrix:
  allow_failures:
  - haxe: development
    
env:
  global:
  # travis encrypt GH_TOKEN=<access-token> -r DoclerLabs/hexMachina
  - secure: Y7k64lsVnGXXFyEttqcYONkQog9pynxGIXnJAa/sdbehdknjQooDQbqWbd2CDzHs1lp7I5kppD3oM8jjkd+7ZH0EjnhzPr2f1OzdcLN3djml2hrKaDr4EMrQW9K3pDCAKP2CtaQtbxjm2l5QHEUcjLe82d/dS5TgEemUPA7/JYM4afCoXpGnCVZcknf5PbR2W3hyFk1R9+8B++5MuH3pNMwZvYEWwzUQLV4GZppe22N7ZlFjLNKnZ9tOd4QcRT9528ujvIKR0K9antuJDBQKTCQqxCTcQmndDp0lEuBhfC9ZDlrMVTLbKUD4B/0g0wHlMKsiJIWo1L03Ec5aASRV4uKRC/4RSLqmY1EXDEuDb1xG4Pg4/NH2Qpqju0qHE/vT5jYNMr2rmnQpcXZEotyoJ70wtIKRR0iIwsSAvTI5SKyNBXg8Wpkqu83/03IfgFqCXPAvOmuv7Pp8zPtLNcz7XnjTiwRFSGvwOzX8jz/+JwCCagLCo6AEcCDT4HCj6hUtHfWdrcyBBHUD40rFJjEDyYyl5MX9yJonznwiWo8Nu3Gx5f4C5WmdEQpxuwUK5wz4uZdH3gpCu7LZyvjUxdPwJNRp5P0uAdptH/vLyVMSyxBG4yC+KFMjWmj65pk0hW0YdS0JcuzgLrtb4r0TvtyElcv04vN7i0sKhY3ai+63IJ8=
  - TRAVIS_NODE_VERSION="6.6.0"

before_install:
  - echo $TRAVIS_BRANCH
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then export DEPENDENCIES_BRANCH=develop; else export DEPENDENCIES_BRANCH=master; fi
  - echo $TRAVIS_TAG
  - if [[ "$TRAVIS_TAG" != "" ]]; then export DEPENDENCIES_BRANCH=$TRAVIS_TAG; fi
  - echo $DEPENDENCIES_BRANCH
  - sudo sed -i -e 's/deb http/deb [arch=amd64] http/' "/etc/apt/sources.list.d/google-chrome.list" "/opt/google/chrome/cron/google-chrome"
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install -qq libcurl3:i386
  - sudo apt-get install -qq libglib2.0-0:i386
  - sudo apt-get install -qq libx11-6:i386
  - sudo apt-get install -qq libxext6:i386
  - sudo apt-get install -qq libxt6:i386
  - sudo apt-get install -qq libxcursor1:i386
  - sudo apt-get install -qq libnss3:i386
  - sudo apt-get install -qq libgtk2.0-0:i386
  
install:
- git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexUnit.git ~/hexunit
- git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexCore.git ~/hexcore
- git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexReflection.git ~/hexreflection
- git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexAnnotation.git ~/hexannotation
- git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexInject.git ~/hexinject
- git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexDsl.git ~/hexdsl
- git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexMVC.git ~/hexmvc
- git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexService.git ~/hexservice
- git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexState.git ~/hexstate
- git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexIoC.git ~/hexioc
- git -C ~/hexannotation log -1 --pretty=oneline
- export DISPLAY=:99.0;
- export AUDIODEV=null;
- haxe flash/install.hxml
- haxelib install dox
- git clone --recursive https://github.com/chipshort/hexDoc-Theme.git ~/hexdoctheme
# update node for deploy scripts
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

before_script:
  - git config --global user.email "laurent@geturl.net"
  - git config --global user.name "Travis-CI"
  
script:
- if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-each.hxml --macro "include('hex')" --no-output -php bin; fi
- if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-php.hxml && php bin/index.php; fi
- haxe build-each.hxml --macro "include('hex')" --no-output -neko bin/docs.n
- if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-neko.hxml && neko bin/TravisMachinaTest.n; fi
- haxe build-each.hxml --macro "include('hex')" --no-output -js bin/docs.js
- haxe build-js.hxml           && node bin/TravisMachinaTest.js
- if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-each.hxml --macro "include('hex')" --no-output -swf-version 11 -swf bin/docs.swf; fi
- if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-flash.hxml -D fdb && haxe flash/run.hxml bin/TravisMachinaTest.swf; fi

before_deploy: "./.travis/pre-deploy.sh"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # travis encrypt <access-token> -r DoclerLabs/hexMachina
    secure: YmXdsL9wqp0jZ/m4VfWAb6sjwm8+3xWAGR3zUQDwr8tPz+pAjNNWxPywgf6iOYJ4rdppfnax/2ay2wrmOobFz159Np2XXmNsgC4xTicEDrFUfzkfUQIMteu/EGqbRbNPaFKRdWFIJcFAqyOuewU1q1w95SaSPSWPvX3UXRR5aaCW+cSErsOTkufxecN5FZawW4VpiOUDQkv69zlKrKddXbrpoKUTPHOob4frAkP3eDypUuwFrWi+3SkpzatjOW54fHyT4e4Lwpg5mJmny/Zh6l5FqbODmAaGf1OUvfNdgHKNn86intqsBv40oc2FQnOmDPkwDjS3MPC37L8jO0foyvLfWOc46xI7jsSm+05lJPyV5mZUHI6elyJ7gcWoSuFBmuDC3WRNcEjTgDAOM3E/15HGbJvVVAJ4Uy0whzoz2ONhQfZ/KC3GEJCbkmoj41MbV36uPm1hchdfDuhcmPucqurs6Hbe1TlknL+2sPkI/UR7FEDmdcCB3B4kFmVSTuO/abp0Xb/PAZMxiI+hdtfvhDAd1RdKfC5wKA7mDxj+jlHa/E1ErUSJqObxNGqxLZcmqRgWS8TSmYaotwo21PKoDsgJXfBOPFO/a0OtZGqhSdRuWBQAm3UQkzMYCwsxetQUjUuL0nRELz41MiL82N964il9WcmCD/H4svXU8Q46pIQ=
  file_glob: true
  file: "*.zip"
  overwrite: true
  on:
    repo: DoclerLabs/hexMachina
    tags: true

after_deploy: "./.travis/post-deploy.sh"

notifications:
  email:
    recipients:
    - francis_bourre@me.com
    - peterphonix@gmail.com
    - laurent@geturl.net
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/09a17f76453cb9d1c34d
    on_success: change
    on_failure: always
    on_start: never
