sudo: required
dist: trusty

language: haxe

haxe:
  #- "3.2.1"
  - development
  #- "3.3.0-rc.1"
# haxe versions : http://haxe.org/website-content/downloads/versions.json

matrix:
  allow_failures:
  - haxe: development
    
install:
- haxelib install travix
- haxelib newrepo
- haxelib install travix
- haxelib git hexunit https://github.com/DoclerLabs/hexUnit.git
- haxelib git hexcore https://github.com/DoclerLabs/hexCore.git
- haxelib git hexinject https://github.com/DoclerLabs/hexInject.git
- haxelib git hexmvc https://github.com/DoclerLabs/hexMVC.git
- haxelib git hexservice https://github.com/DoclerLabs/hexService.git
- haxelib git hexstate https://github.com/DoclerLabs/hexState.git
- haxelib git hexioc https://github.com/DoclerLabs/hexIoC.git
- haxelib git hexannotation https://github.com/DoclerLabs/hexAnnotation.git
#- haxe flash/install.hxml
- haxelib dev hexmachina .
- haxelib path hexmachina

script:
- if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxelib run travix php;
  fi
- if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxelib run travix neko;
  fi
- haxelib run travix js
- haxelib run travix flash

before_deploy: "./release-hexMachina-bundle.sh"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ebMXJ+/Go7G2j/Ultg183WBvAElOKymePuGxBZe0lUSIlVECvXZF7wikI+jek4PGy914/FagdDyUGeTWGvrfA/fOjhBNFXBqVwWulXFzYG+Fk2iPfHco6efyUh+ysliKrCrXuzYjaqz1xqON0ORnRkHQ0sex0swsYGSHa9zpG2rpJGIjoErHdUL369iYkEPN3eq0Rkl2+YgygiI+YUmnsrAYfh00GqptyGwNJpmRePK/xXqhZPSsE71nCvYOxbBqyn//x4jt7DlyxbuMa0vbBHnTbUr717bKdzkZjf0JJF8Rh/QoPG5NiipzLpMuG6UwdeFMUQw5We5vIydC5qEMI+jhNU0NsAW6jujKYl/L8QsSxpWnRzEC7NJeZ6ykZoZU9RUZgxFDVALMZg2veNb51GIb8iQ+CiXZrPvObNMwrk7ni3qu1BsNIbVcJHa6Ev59z9uc4oJ/DROk1GO3f2ByIXiQYe+RITy0Urb8CG83Xu8tHmsHg/H5A9/6Nvk2qoRlIUtcf6RXmy6+zEzT25XgfounHVuGm58obMCZNzOOGf9XHZYH55drIYuj2uUeQomFiHOhGKz4TRWFcInCchM4Wz3VN1ObCLUI+zhT+Q4sri1geIhD5hdY2tgl5rUX6gNR3UVbXkQWu1DnvoSn/J/QoHVWZ8k/GiP1fgAglB2jFjU=
  file_glob: true
  file: "*.zip"
  overwrite: true
  on:
    repo: DoclerLabs/hexMachina
    tags: true

notifications:
  email:
    recipients:
    - francis_bourre@me.com
    - peterphonix@gmail.com
    - laurent@geturl.net
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/09a17f76453cb9d1c34d
    on_success: change
    on_failure: always
    on_start: never
