sudo: required
dist: trusty

language: haxe

os:
  - linux

# haxe versions : http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.7"
  - development

env:
  global:
    # travis encrypt GH_TOKEN=<access-token> -r DoclerLabs/hexMachina
    - secure: Y7k64lsVnGXXFyEttqcYONkQog9pynxGIXnJAa/sdbehdknjQooDQbqWbd2CDzHs1lp7I5kppD3oM8jjkd+7ZH0EjnhzPr2f1OzdcLN3djml2hrKaDr4EMrQW9K3pDCAKP2CtaQtbxjm2l5QHEUcjLe82d/dS5TgEemUPA7/JYM4afCoXpGnCVZcknf5PbR2W3hyFk1R9+8B++5MuH3pNMwZvYEWwzUQLV4GZppe22N7ZlFjLNKnZ9tOd4QcRT9528ujvIKR0K9antuJDBQKTCQqxCTcQmndDp0lEuBhfC9ZDlrMVTLbKUD4B/0g0wHlMKsiJIWo1L03Ec5aASRV4uKRC/4RSLqmY1EXDEuDb1xG4Pg4/NH2Qpqju0qHE/vT5jYNMr2rmnQpcXZEotyoJ70wtIKRR0iIwsSAvTI5SKyNBXg8Wpkqu83/03IfgFqCXPAvOmuv7Pp8zPtLNcz7XnjTiwRFSGvwOzX8jz/+JwCCagLCo6AEcCDT4HCj6hUtHfWdrcyBBHUD40rFJjEDyYyl5MX9yJonznwiWo8Nu3Gx5f4C5WmdEQpxuwUK5wz4uZdH3gpCu7LZyvjUxdPwJNRp5P0uAdptH/vLyVMSyxBG4yC+KFMjWmj65pk0hW0YdS0JcuzgLrtb4r0TvtyElcv04vN7i0sKhY3ai+63IJ8=
  matrix:
    - HAXE_TARGET=cpp
    #- HAXE_TARGET=cs
    - HAXE_TARGET=flash
    #- HAXE_TARGET=lua
    - HAXE_TARGET=neko
    - HAXE_TARGET=node
    - HAXE_TARGET=php
    - HAXE_TARGET=php7
    #- HAXE_TARGET=python
    - HAXE_TARGET=js
    #- HAXE_TARGET=java
    - HAXE_TARGET=hl

matrix:
  fast_finish: true
  allow_failures:
    - haxe: development
    - env: HAXE_TARGET=flash # cannot trust that guy
    - env: HAXE_TARGET=cpp # Not supported yet
    - env: HAXE_TARGET=cs # Not supported yet
    - env: HAXE_TARGET=lua # Not supported yet
    - env: HAXE_TARGET=python # Not supported yet
    - env: HAXE_TARGET=java # Not supported yet
    - env: HAXE_TARGET=hl # Not supported yet
  exclude:
    - haxe: "3.4.7"
      env: HAXE_TARGET=hl

before_install:
  - echo $TRAVIS_BRANCH
  - export DEPENDENCIES_BRANCH=$TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - if [[ "$TRAVIS_TAG" != "" ]]; then export DEPENDENCIES_BRANCH=$TRAVIS_TAG; fi
  - echo $DEPENDENCIES_BRANCH

install:
  - export BRANCH_REF=$DEPENDENCIES_BRANCH
  - haxelib install travix --always
# hexLog
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexLog.git $BRANCH_REF | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexLog.git ~/hexlog
  - haxelib dev hexlog ~/hexlog
# hexCore
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexCore.git $BRANCH_REF | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexCore.git ~/hexcore
  - haxelib install ~/hexcore/haxelib.json --always
  - haxelib dev hexcore ~/hexcore
# hexUnit
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexUnit.git $BRANCH_REF | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexUnit.git ~/hexunit
  - haxelib dev hexunit ~/hexunit
# hexReflection
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexReflection.git $BRANCH_REF | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexReflection.git ~/hexreflection
  - haxelib dev hexreflection ~/hexreflection
# hexAnnotation
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexAnnotation.git $BRANCH_REF | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexAnnotation.git ~/hexannotation
  - haxelib dev hexannotation ~/hexannotation
# hexInject
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexInject.git $BRANCH_REF | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexInject.git ~/hexinject
  - haxelib dev hexinject ~/hexinject
# hexDsl
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexDsl.git $BRANCH_REF | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexDsl.git ~/hexdsl
  - haxelib dev hexdsl ~/hexdsl
# hexCommand
  - if [ $( git ls-remote https://github.com/DoclerLabs/hexCommand.git $BRANCH_REF | wc -l ) == "0" ]; then export DEPENDENCIES_BRANCH=master; else export DEPENDENCIES_BRANCH=$BRANCH_REF; fi
  - echo Checking out $DEPENDENCIES_BRANCH
  - git clone --recursive -b $DEPENDENCIES_BRANCH https://github.com/DoclerLabs/hexCommand.git ~/hexcommand
  - haxelib dev hexcommand ~/hexcommand
#hexMachina
  - haxelib dev hexmachina .
  - haxelib path hexcommand
  - git clone --recursive https://github.com/chipshort/hexDoc-Theme.git ~/hexdoctheme

before_script:
  - git config --global user.email "laurent@geturl.net"
  - git config --global user.name "Travis-CI"
  
script:
  - haxelib run travix $HAXE_TARGET

before_deploy:
  - if [ $TRAVIS_HAXE_VERSION == "3.4.7" && ]; then ./.travis/pre-deploy.sh; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # travis encrypt <access-token> -r DoclerLabs/hexMachina
    secure: YmXdsL9wqp0jZ/m4VfWAb6sjwm8+3xWAGR3zUQDwr8tPz+pAjNNWxPywgf6iOYJ4rdppfnax/2ay2wrmOobFz159Np2XXmNsgC4xTicEDrFUfzkfUQIMteu/EGqbRbNPaFKRdWFIJcFAqyOuewU1q1w95SaSPSWPvX3UXRR5aaCW+cSErsOTkufxecN5FZawW4VpiOUDQkv69zlKrKddXbrpoKUTPHOob4frAkP3eDypUuwFrWi+3SkpzatjOW54fHyT4e4Lwpg5mJmny/Zh6l5FqbODmAaGf1OUvfNdgHKNn86intqsBv40oc2FQnOmDPkwDjS3MPC37L8jO0foyvLfWOc46xI7jsSm+05lJPyV5mZUHI6elyJ7gcWoSuFBmuDC3WRNcEjTgDAOM3E/15HGbJvVVAJ4Uy0whzoz2ONhQfZ/KC3GEJCbkmoj41MbV36uPm1hchdfDuhcmPucqurs6Hbe1TlknL+2sPkI/UR7FEDmdcCB3B4kFmVSTuO/abp0Xb/PAZMxiI+hdtfvhDAd1RdKfC5wKA7mDxj+jlHa/E1ErUSJqObxNGqxLZcmqRgWS8TSmYaotwo21PKoDsgJXfBOPFO/a0OtZGqhSdRuWBQAm3UQkzMYCwsxetQUjUuL0nRELz41MiL82N964il9WcmCD/H4svXU8Q46pIQ=
  file_glob: true
  file: "*.zip"
  overwrite: true
  on:
    repo: DoclerLabs/hexMachina
    tags: true

after_deploy:
- if [ $TRAVIS_HAXE_VERSION == "3.4.7" ] && [ $HAXE_TARGET == "flash" ]; then ./.travis/post-deploy.sh; fi

notifications:
  email:
    recipients:
    - francis_bourre@me.com
    - peterphonix@gmail.com
    - laurent@geturl.net
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/09a17f76453cb9d1c34d
    on_success: change
    on_failure: always
    on_start: never
