sudo: required
dist: trusty

language: haxe

haxe:
  - "3.2.1"
  - development
  - "3.3.0-rc.1"
# haxe versions : http://haxe.org/website-content/downloads/versions.json

addons:
  apt:
    packages:
      # PHP
      # - php5-cli
      # Flash
      - libcurl3:i386
      - libglib2.0-0:i386
      - libx11-6:i386
      - libxext6:i386
      - libxt6:i386
      - libxcursor1:i386
      - libnss3:i386
      - libgtk2.0-0:i386
matrix:
  allow_failures:
  - haxe: development
    
install:
- git clone --recursive https://github.com/DoclerLabs/hexUnit.git ~/hexunit
- git clone --recursive https://github.com/DoclerLabs/hexCore.git ~/hexcore
- git clone --recursive https://github.com/DoclerLabs/hexInject.git ~/hexinject
- git clone --recursive https://github.com/DoclerLabs/hexMVC.git ~/hexmvc
- git clone --recursive https://github.com/DoclerLabs/hexService.git ~/hexservice
- git clone --recursive https://github.com/DoclerLabs/hexState.git ~/hexstate
- git clone --recursive https://github.com/DoclerLabs/hexIoC.git ~/hexioc
- git clone --recursive https://github.com/DoclerLabs/hexAnnotation.git ~/hexannotation
- haxe flash/install.hxml
- haxelib install travix

script:
- if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxelib run travix php build-php.hxml;
  fi
- if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-neko.hxml && neko bin/TravisMachinaTest.n;
  fi
- haxe build-js.hxml           && node bin/TravisMachinaTest.js
- haxe build-flash.hxml -D fdb && haxe flash/run.hxml bin/TravisMachinaTest.swf

before_deploy: "./release-hexMachina-bundle.sh"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ebMXJ+/Go7G2j/Ultg183WBvAElOKymePuGxBZe0lUSIlVECvXZF7wikI+jek4PGy914/FagdDyUGeTWGvrfA/fOjhBNFXBqVwWulXFzYG+Fk2iPfHco6efyUh+ysliKrCrXuzYjaqz1xqON0ORnRkHQ0sex0swsYGSHa9zpG2rpJGIjoErHdUL369iYkEPN3eq0Rkl2+YgygiI+YUmnsrAYfh00GqptyGwNJpmRePK/xXqhZPSsE71nCvYOxbBqyn//x4jt7DlyxbuMa0vbBHnTbUr717bKdzkZjf0JJF8Rh/QoPG5NiipzLpMuG6UwdeFMUQw5We5vIydC5qEMI+jhNU0NsAW6jujKYl/L8QsSxpWnRzEC7NJeZ6ykZoZU9RUZgxFDVALMZg2veNb51GIb8iQ+CiXZrPvObNMwrk7ni3qu1BsNIbVcJHa6Ev59z9uc4oJ/DROk1GO3f2ByIXiQYe+RITy0Urb8CG83Xu8tHmsHg/H5A9/6Nvk2qoRlIUtcf6RXmy6+zEzT25XgfounHVuGm58obMCZNzOOGf9XHZYH55drIYuj2uUeQomFiHOhGKz4TRWFcInCchM4Wz3VN1ObCLUI+zhT+Q4sri1geIhD5hdY2tgl5rUX6gNR3UVbXkQWu1DnvoSn/J/QoHVWZ8k/GiP1fgAglB2jFjU=
  file_glob: true
  file: "*.zip"
  overwrite: true
  on:
    repo: DoclerLabs/hexMachina
    tags: true

notifications:
  email:
    recipients:
    - francis_bourre@me.com
    - peterphonix@gmail.com
    - laurent@geturl.net
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/09a17f76453cb9d1c34d
    on_success: change
    on_failure: always
    on_start: never
