language: haxe

haxe:
  - development

addons:
  apt:
    packages:
      # Flash
      - libcurl3:i386
      - libglib2.0-0:i386
      - libx11-6:i386
      - libxext6:i386
      - libxt6:i386
      - libxcursor1:i386
      - libnss3:i386
      - libgtk2.0-0:i386

install:
  - git clone --recursive https://github.com/DoclerLabs/hexUnit.git ~/hexunit
  - git clone --recursive https://github.com/DoclerLabs/hexCore.git ~/hexcore
  - git clone --recursive https://github.com/DoclerLabs/hexInject.git ~/hexinject
  - git clone --recursive https://github.com/DoclerLabs/hexMVC.git ~/hexmvc
  - git clone --recursive https://github.com/DoclerLabs/hexService.git ~/hexservice
  - git clone --recursive https://github.com/DoclerLabs/hexState.git ~/hexstate
  - git clone --recursive https://github.com/DoclerLabs/hexIoC.git ~/hexioc
  - export DISPLAY=:99.0;
  - export AUDIODEV=null;
  - haxe flash/install.hxml

script:
  - haxe build-js.hxml           && node bin/TravisMachinaTest.js
  - haxe build-flash.hxml -D fdb && haxe flash/run.hxml bin/TravisMachinaTest.swf
  
notifications:
  email:
    recipients:
      - francis_bourre@me.com
      - peterphonix@gmail.com
