language: haxe

haxe:
  - "3.2.1"
  - development

addons:
  apt:
    packages:
      # PHP
      - php5-cli
      # Flash
      - libcurl3:i386
      - libglib2.0-0:i386
      - libx11-6:i386
      - libxext6:i386
      - libxt6:i386
      - libxcursor1:i386
      - libnss3:i386
      - libgtk2.0-0:i386

install:
  - git clone --recursive https://github.com/DoclerLabs/hexUnit.git ~/hexunit
  - git clone --recursive https://github.com/DoclerLabs/hexCore.git ~/hexcore
  - git clone --recursive https://github.com/DoclerLabs/hexInject.git ~/hexinject
  - git clone --recursive https://github.com/DoclerLabs/hexMVC.git ~/hexmvc
  - git clone --recursive https://github.com/DoclerLabs/hexService.git ~/hexservice
  - git clone --recursive https://github.com/DoclerLabs/hexState.git ~/hexstate
  - git clone --recursive https://github.com/DoclerLabs/hexIoC.git ~/hexioc
  - git clone --recursive https://github.com/DoclerLabs/hexAnnotation.git ~/hexannotation
  - export DISPLAY=:99.0;
  - export AUDIODEV=null;
  - haxe flash/install.hxml

script:
  - echo TRAVIS_HAXE_VERSION
  - echo $TRAVIS_HAXE_VERSION
  - if [ TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-php.hxml && php bin/index.php; fi
  - haxe build-js.hxml           && node bin/TravisMachinaTest.js
  - haxe build-flash.hxml -D fdb && haxe flash/run.hxml bin/TravisMachinaTest.swf
  
notifications:
  email:
    recipients:
      - francis_bourre@me.com
      - peterphonix@gmail.com
      - laurent@geturl.net
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/09a17f76453cb9d1c34d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
