# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HEXMACHINA - a powerful multi-modular MVC framework written in Haxe
email: info@hexmachina.org
description: A powerful multi-modular MVC+S system written in Haxe
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hexmachina.org/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  DoclerLabs

# Build settings
markdown: kramdown

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-seo-tag

lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
exclude: [".git", "hex*", "build.bat", "build"]

disqus_shortname: hexmachina
disqus_publickey: nB9WCx4oEOsvmKPvKtoGtIxp2xre054EU7c7kqHyn09BoP1skkTDw109FXJSAOVJ
